package com.ryan.doubletrack.wage.entity;


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.hibernate.annotations.GenericGenerator;

import com.ryan.framework.entity.Model;

/**
 * Wage generated by hbm2java
 */
@Entity
@Table(name = "wage", catalog = "doubletrack")
public class Wage implements Model {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long wageId;
	private Long customerId;
	private String customerCode;
	private String customerName;
	private String phone;
	private String idCardNumber;
	private String bankType;
	private String bankAccount;
	private Float salary;
	private Date createTime;
	private Date startCreateTime;
	private Date endCreateTime;
	private Date lastModifyTime;

	public Wage() {
	}

	public Wage(Long wageId) {
		this.wageId = wageId;
	}

	public Wage(Long wageId, Long customerId, Float salary, Date createTime,
			Date lastModifyTime) {
		this.wageId = wageId;
		this.customerId = customerId;
		this.salary = salary;
		this.createTime = createTime;
		this.lastModifyTime = lastModifyTime;
	}

	@Id
	@GenericGenerator(name = "generator", strategy = "increment")
	@GeneratedValue(generator = "generator")
	@Column(name = "wage_id", unique = true, nullable = false)
	public Long getWageId() {
		return this.wageId;
	}

	public void setWageId(Long wageId) {
		this.wageId = wageId;
	}

	@Column(name = "customer_id")
	public Long getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(Long customerId) {
		this.customerId = customerId;
	}

	@Column(name = "customer_code", length = 20)
	public String getCustomerCode() {
		return this.customerCode;
	}

	public void setCustomerCode(String customerCode) {
		this.customerCode = customerCode;
	}

	@Column(name = "customer_name", length = 30)
	public String getCustomerName() {
		return this.customerName;
	}

	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	@Column(name = "phone", length = 50)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "id_card_number", length = 50)
	public String getIdCardNumber() {
		return this.idCardNumber;
	}

	public void setIdCardNumber(String idCardNumber) {
		this.idCardNumber = idCardNumber;
	}

	@Column(name = "bank_type", length = 20)
	public String getBankType() {
		return this.bankType;
	}

	public void setBankType(String bankType) {
		this.bankType = bankType;
	}

	@Column(name = "bank_account", length = 50)
	public String getBankAccount() {
		return this.bankAccount;
	}

	public void setBankAccount(String bankAccount) {
		this.bankAccount = bankAccount;
	}

	@Column(name = "salary", precision = 11)
	public Float getSalary() {
		return this.salary;
	}

	public void setSalary(Float salary) {
		this.salary = salary;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Transient
	public Date getStartCreateTime() {
		return startCreateTime;
	}

	public void setStartCreateTime(Date startCreateTime) {
		this.startCreateTime = startCreateTime;
	}

	@Transient
	public Date getEndCreateTime() {
		return endCreateTime;
	}

	public void setEndCreateTime(Date endCreateTime) {
		this.endCreateTime = endCreateTime;
	}


	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_modify_time", length = 19)
	public Date getLastModifyTime() {
		return this.lastModifyTime;
	}

	public void setLastModifyTime(Date lastModifyTime) {
		this.lastModifyTime = lastModifyTime;
	}

}
