package com.ryan.doubletrack.customer.entity;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.criteria.CriteriaBuilder.In;

import org.hibernate.annotations.GenericGenerator;

import com.ryan.framework.entity.Model;

/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name = "customer")
public class Customer implements Model{

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long customerId;
	private String customerCode;
	private String customerName;
	private Integer customerType;
	private Integer level;
	private String phone;
	private String contact;
	private String idCardNumber;
	private String qq;
	private String bankType;
	private String bankAccount;
	private String address;
	private String email;//客户邮箱
//	private Long parentCustomerId;
//	private Long recommendCustomerId;
	private Customer parentCustomer;
	private Customer recommendCustomer;
	private String customerSequence;
	private Integer status;
	private Integer activatStatus;  //0-都未激活；1-手机号激活；2-邮箱激活；3-都激活
	private String remark;

	public Customer() {
	}

	public Customer(Long customerId, String customerCode, String customerName) {
		this.customerId = customerId;
		this.customerCode = customerCode;
		this.customerName = customerName;
	}

	public Customer(Long customerId, String customerCode, String customerName,
			Integer customerType, Integer level,String phone, String contact,
			String idCardNumber, String qq, String bankType,
			String bankAccount, String address, Long parentCustomerId,
			Long recommendCustomerId, String customerSequence) {
		this.customerId = customerId;
		this.customerCode = customerCode;
		this.customerName = customerName;
		this.customerType = customerType;
		this.level = level;
		this.phone = phone;
		this.contact = contact;
		this.idCardNumber = idCardNumber;
		this.qq = qq;
		this.bankType = bankType;
		this.bankAccount = bankAccount;
		this.address = address;
//		this.parentCustomerId = parentCustomerId;
//		this.recommendCustomerId = recommendCustomerId;
		this.customerSequence = customerSequence;
	}

	@Id
	@GenericGenerator(name = "generator", strategy = "increment")
	@GeneratedValue(generator = "generator")
	@Column(name = "customer_id", unique = true, nullable = false)
	public Long getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(Long customerId) {
		this.customerId = customerId;
	}

	@Column(name = "customer_code", nullable = false, length = 20)
	public String getCustomerCode() {
		return this.customerCode;
	}

	public void setCustomerCode(String customerCode) {
		this.customerCode = customerCode;
	}

	@Column(name = "customer_name", nullable = false, length = 30)
	public String getCustomerName() {
		return this.customerName;
	}

	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	@Column(name = "customer_type")
	public Integer getCustomerType() {
		return this.customerType;
	}

	public void setCustomerType(Integer customerType) {
		this.customerType = customerType;
	}

	@Column(name = "level")
	public Integer getLevel() {
		return this.level;
	}

	public void setLevel(Integer level) {
		this.level = level;
	}
	@Column(name = "phone", length = 50)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "contact", length = 50)
	public String getContact() {
		return this.contact;
	}

	public void setContact(String contact) {
		this.contact = contact;
	}

	@Column(name = "id_card_number", length = 50)
	public String getIdCardNumber() {
		return this.idCardNumber;
	}

	public void setIdCardNumber(String idCardNumber) {
		this.idCardNumber = idCardNumber;
	}

	@Column(name = "qq", length = 50)
	public String getQq() {
		return this.qq;
	}

	public void setQq(String qq) {
		this.qq = qq;
	}

	@Column(name = "bank_type")
	public String getBankType() {
		return this.bankType;
	}

	public void setBankType(String bankType) {
		this.bankType = bankType;
	}

	@Column(name = "bank_account", length = 50)
	public String getBankAccount() {
		return this.bankAccount;
	}

	public void setBankAccount(String bankAccount) {
		this.bankAccount = bankAccount;
	}

	@Column(name = "address", length = 256)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "customer_sequence", length = 1024)
	public String getCustomerSequence() {
		return this.customerSequence;
	}

	public void setCustomerSequence(String customerSequence) {
		this.customerSequence = customerSequence;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "remark", length = 1024)
	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@OneToOne( cascade = {CascadeType.PERSIST,CascadeType.REFRESH,CascadeType.DETACH}, targetEntity=Customer.class )
	@JoinColumn(name="parent_customer_id")
	public Customer getParentCustomer() {
		return parentCustomer;
	}

	public void setParentCustomer(Customer parentCustomer) {
		this.parentCustomer = parentCustomer;
	}

	@OneToOne( cascade = {CascadeType.PERSIST,CascadeType.REFRESH,CascadeType.DETACH}, targetEntity=Customer.class )
	@JoinColumn(name="recommend_customer_id")
	public Customer getRecommendCustomer() {
		return recommendCustomer;
	}

	public void setRecommendCustomer(Customer recommendCustomer) {
		this.recommendCustomer = recommendCustomer;
	}

	@Column(name = "activat_status")
	public Integer getActivatStatus() {
		return activatStatus;
	}

	public void setActivatStatus(Integer activatStatus) {
		this.activatStatus = activatStatus;
	}
	@Column(name = "email", length = 128)
	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

}
